name: Build and Deploy Full Application to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build backend with Maven
      run: mvn clean install
      working-directory: ./backend/market-ticker/

    - name: Build frontend with Angular
      run: |
        npm install
        npm run build --prod
      working-directory: ./frontend/market-ticker-app/

    - name: Copy frontend to backend static resources
      run: |
        mkdir -p ./backend/market-ticker/src/main/resources/static
        cp -r ./frontend/market-ticker-app/dist/market-ticker-app/browser/* ./backend/market-ticker/src/main/resources/static/
      shell: bash

    - name: Package backend
      run: mvn clean package
      working-directory: ./backend/market-ticker/

    - name: Upload to S3
      run: aws s3 cp ./backend/market-ticker/target/*.jar s3://$S3_BUCKET/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}

    - name: Deploy to Elastic Beanstalk
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        JAR_FILE=$(ls backend/market-ticker/target | grep .jar | head -n 1)
        VERSION_LABEL="${GITHUB_SHA}-${TIMESTAMP}"
        aws elasticbeanstalk create-application-version --application-name $EB_APPLICATION --version-label $VERSION_LABEL --source-bundle S3Bucket=$S3_BUCKET,S3Key=$JAR_FILE
        aws elasticbeanstalk update-environment --environment-name $EB_ENVIRONMENT --version-label $VERSION_LABEL
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EB_APPLICATION: ${{ secrets.EB_APPLICATION }}
        EB_ENVIRONMENT: ${{ secrets.EB_ENVIRONMENT }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
